# Generated by Django 4.1.1 on 2023-02-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(default=None, max_length=899, null=True, upload_to='docs/'),
        ),
    ]
